### ISSUE TITLE
MatrixDouble not found (polylidar 3d)

### ISSUE THREAD

**Issue by sivashankar28** [JeremyBYU/polylidar-realsense#2]
Hi, I was trying to run your code but I keep getting MatrixDouble not found when trying to execute capture_ga.py.
I believe it is not calling the polylidar file in capture_ga.py. 
How do I correct it so that it recognizes the correct file?

**Comment by JeremyBYU** [comment]
It sounds like you are not on the master branch. Only the master branch is working fully right now. The Polylidar3d branch is not really ready yet for others to consume yet.

It should be ready sometime in the next month. Sorry about that!

**Comment by JeremyBYU** [comment]
To be more clear there the entire build system for Polylidar has changed to Cmake and it relies upon other repositories that I built. Some of which that are private. Hence it will take time to get everything in sync.

**Comment by sivashankar28** [comment]
Thank you! I appreciate the response and feedback!

**Comment by JeremyBYU** [comment]
When I'm ready with the final release I would like to work with you to test out Polylidar3d. My email is in profile and you can contact me if you are interested. If not no problem and I'll just ping this thread when it's ready.

**Comment by johntranz** [comment]
@JeremyBYU Now the profiles are in sync?, can you make it connect to real-time with the Realsense camera, I followed the steps and still can't run capture.py (ImportError: cannot import name 'MatrixDouble'). Waiting for your response

**Comment by JeremyBYU** [comment]
Jane-Tran,
The branch `master` now has Polylidar3D. However,  you need to install Polylidar3D from source following the installation instructions found here: https://jeremybyu.github.io/polylidar/install_instructions.html#id1


My guess is you installed from pip. That is a very very old version that has no proper 3D support.
