### ISSUE TITLE
CUDA required?

### ISSUE THREAD

**Issue by oori** [JeremyBYU/polylidar-realsense#5]
Hello

Trying to run on Ubuntu with L515, with python 3.8.5: 
`python3 -m surfacedetector.capture -c surfacedetector/config/l515.yaml`
_(only changed playback.enabled to `false`, for live streaming)_

I get error:
```
oori@oobuntu:~/polylidar/polylidar-realsense$ python3 -m surfacedetector.capture -c surfacedetector/config/l515.yaml
Found Intel RealSense L515
/home/oori/polylidar/polylidar-realsense/surfacedetector/capture.py:124: DeprecationWarning: an integer is required (got type pyrealsense2.format).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  rs_config.enable_stream(
/home/oori/polylidar/polylidar-realsense/surfacedetector/capture.py:129: DeprecationWarning: an integer is required (got type pyrealsense2.format).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  rs_config.enable_stream(
INFO - 2020-12-14 00:16:14,714 - capture - Pipeline Created
ERROR - 2020-12-14 00:16:16,000 - capture - Error!
Traceback (most recent call last):
  File "/home/oori/polylidar/polylidar-realsense/surfacedetector/capture.py", line 408, in capture
    planes, obstacles, timings = get_polygon(depth_image, config, ll_objects, **meta)
  File "/home/oori/polylidar/polylidar-realsense/surfacedetector/capture.py", line 294, in get_polygon
    mesh, timings = create_meshes_cuda(opc, **config['mesh']['filter'])
  File "/home/oori/polylidar/polylidar-realsense/surfacedetector/utility/helper_mesh.py", line 471, in create_meshes_cuda
    smooth_opc, opc_normals, timings = laplacian_then_bilateral_opc_cuda(opc, **kwargs)
  File "/home/oori/polylidar/polylidar-realsense/surfacedetector/utility/helper_mesh.py", line 360, in laplacian_then_bilateral_opc_cuda
    import organizedpointfilters.cuda as opf_cuda
  File "/home/oori/polylidar/OrganizedPointFilters/cmake-build/lib/python_package/organizedpointfilters/cuda/__init__.py", line 1, in <module>
    import organizedpointfilters.cuda.kernel
  File "/home/oori/polylidar/OrganizedPointFilters/cmake-build/lib/python_package/organizedpointfilters/cuda/kernel.py", line 5, in <module>
    import cupy as cp
ModuleNotFoundError: No module named 'cupy'
```

Running on system without Nvidia gfx card, so I can't install `cupy`.     I saw they have experimental ROCm support for AMD chipset, but I was wondering if we can't just use plain old `numpy` ?
Looking at your https://github.com/JeremyBYU/OrganizedPointFilters, it seems that actually [GPU acceleration](https://jeremybyu.github.io/OrganizedPointFilters/tutorial/Python/basic.html#GPU-Acceleration) is  **optional**. Did i miss a flag somewhere?

Also, had a hard time getting all dependencies installed, tried both ubuntu (amd64) and RPi (arm).  I've documented the process and will send docs PR later, if I get it to really work.

Thanks for your efforts, superb pieces of code!

**Comment by JeremyBYU** [comment]
Hi thanks for checking this out. I *think* that I configured the code to use cupy/cuda at runtime. I believe you only need to change the parameter 'use_cuda' in the config L515.yaml file. Set that to false and I hope that it will work. 
https://github.com/JeremyBYU/polylidar-realsense/blob/280ed6749aace0169d0168ede3951207fefcc5f9/surfacedetector/config/l515.yaml#L49

I can see in the stack trace that you are calling the create_meshes_cuda which should only be called if use_cuda is true.


Note that this is likely going to be pretty slow on rpi4. I have run polylidar on Rpi4 and it runs okay. But I have not run the mesh smoothing code, fastga, which is pretty demanding! Look forward to your notes on installing it on the PI!

**Comment by oori** [comment]
Oh... I can't believe I missed it.    Now it works (on Ubuntu).
On RPi I couldn't build `OrganizedPointFilters` successfully.  I'll open a separate issue there.

I'll start playing on Ubuntu first, and update the docs. Thanks again!

**Comment by JeremyBYU** [comment]
No prob, I don't really have any docs yet! 

Sorry to hear that OPF didn't compile on rpi4!definitely open up an issue in that repo and I'll try to track it down as well maybe sometime Christmas break.

**Comment by oori** [comment]
Jeremy, as the docs are WIP, it'll take more time to get them nicely wrapped. My students are slowly trying to test and reproduce.   I'm adding you to a private repo, so you can track this. Thanks.
