### ISSUE TITLE
AttributeError: module 'pyrealsense2' has no attribute 'stream'

### ISSUE THREAD

**Issue by dorinseggall** [JeremyBYU/polylidar-realsense#6]
Hi ,
i am trying to activate the code with the D435i , i am working on Ubuntu (with oracle VM Virtual)
i finish all the clones process and try to run -
python3 -m surfacedetector.capture.py -c urfacedetector/config/default.yaml
and i received the next error :

Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
import(pkg_name)
File "/home/dorinse/dorin/polylidar-realsense/surfacedetector/capture.py", line 23, in
from surfacedetector.utility.helper import (plot_planes_and_obstacles, create_projection_matrix,
File "/home/dorinse/dorin/polylidar-realsense/surfacedetector/utility/helper.py", line 83, in
def get_intrinsics(pipeline, stream=rs.stream.color):
AttributeError: module 'pyrealsense2' has no attribute 'stream'
can you help me , any idea ?
thank you !

**Comment by JeremyBYU** [comment]
Hi dorinseggall,
I think this may indicate that your realsense installation is broken. Can you maybe check that you can can run a python script which accesses your camera. 

Basically, can you run this script: https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/pyglet_pointcloud_viewer.py

If the script errors, you will have to go to the RealSense GitHub repo and try to figure out how to get your system up and running for your cameras.

Thanks

**Comment by oori** [comment]
@JeremyBYU Yes, `pyrealsense` wasn't available on her installation.
You can close this issue, thanks.

**Comment by JeremyBYU** [comment]
No problem!
