### ISSUE TITLE
demo code not running

### ISSUE THREAD

**Issue by nawara72** [JeremyBYU/polylidar-realsense#7]
Hi Thank you for sharing your code, I am really interested in trying it out. I have installed according to your instructions, however when i run
python -m surfacedetector.capture
The code seems to exit when executing the following line in the demo
rs_config.enable_stream(...

Would really appreciate your help in getting it to work

Thanks

**Comment by nawara72** [comment]
I was able to get it to work by simply disabling Cuda, now it is working however if I try to inrease depth and rgb image size it fails

Do the sizes have to be 424 by 240?

Thanks

**Comment by JeremyBYU** [comment]
Thanks for checking out the code. It can definitely handle higher resolutions but will be slower. Unfortunately I don't have a lot of information to go off in your comment besides "failure". It would be nice if you could describe the failure and copy full stack traces.

Also here is another issue that might come in handy: https://github.com/JeremyBYU/polylidar-realsense/issues/4

The most important thing is to first make sure the depth image is coming in alright. Dial in realsense  postprocessing filters first. Then mess around with the others.
