### ISSUE TITLE
Broken since FGA update

### ISSUE THREAD

**Issue by oori** [JeremyBYU/polylidar-realsense#8]
`fastga` --> `fastgac`,  and `find_peaks_from_ico_charts()` removed.

https://github.com/JeremyBYU/FastGaussianAccumulator/commit/578276e188268c526d726454fbcee8131f53973d

**Comment by JeremyBYU** [comment]
The rename was definitely a breaking change. I will need to update this repo for the new fastgac name. 

However that function you highlighted was a work in progress that was added and renamed in 1 day in a dev branch. The peak detection API that used to be performed is still on the master branch. All the original python API still works that relies upon sklearn and scipy. I didn't remove it. I just added a cpp code that removes python libraries from being a hard dependency.


I will try and update this repo soon.

**Comment by oori** [comment]
Thanks for the quick reply.    I did the renames, but then I hit this `find_peaks_from_ico_charts()` error (used [here](https://github.com/JeremyBYU/polylidar-realsense/blob/280ed6749aace0169d0168ede3951207fefcc5f9/surfacedetector/utility/helper_polylidar.py#L122)).   I'll check it again.

**Comment by JeremyBYU** [comment]
Thanks @oori,
I'm not sure why it erred on calling that Python function. Sorry about that.
However, I have updated the repo a few moments ago. It should be working fine now with a new updated FastGA and this repo. Be sure to pull from both (master branch). I only tested this on windows but should work fine on Linux as well.

I didn't make any big changes in this repo but am now using the function [find_peaks](https://jeremybyu.github.io/FastGaussianAccumulator/python_api/fastgac.GaussianAccumulatorS2Beta.html#fastgac.GaussianAccumulatorS2Beta) which is a method on `FastGaussianAccumularS2Beta` class. This is the class that I use now that has been much improved for my work. The method is implemented entirely in C++ and does not rely upon `sklean-image` or `scipy` for image feature detection or agglomerative hierarchical clustering.


I know the class is has "Beta" in it but it is working much better for me.  However if there are issues you can revert back to the previous GaussianAccumulator this repo was using FastGaussianAccumulatorS2. Nothing was removed, only added.

Let mew know if this fixes your issues.

**Comment by oori** [comment]
Just tested new commits today on Linux. Works great, thanks!
